"""Run the conservative Hermes grader and emit per-run annotation proposals.

This produces deliverables for T2 (annotate 30 Hermes runs upstream). It does
**not** mutate any file under ../coding-progress-ledger/. The output is a
proposal package the upstream annotator reviews before committing labels.
"""

from __future__ import annotations

from pathlib import Path

from coding_estimator.labels.hermes_terminal_grader import (
    HermesGrade,
    grade_source,
)

UPSTREAM = Path(__file__).resolve().parents[1].parent / "coding-progress-ledger"
SOURCE_RUNS = UPSTREAM / "runs" / "hermes_pilot_h5_v2"
OUT_DIR = Path(__file__).resolve().parents[1] / "reports" / "hermes_annotation_proposals"


def _per_run_md(g: HermesGrade) -> str:
    fs = "false" if g.proposed_final_success is False else (
        "true" if g.proposed_final_success is True else "null (needs human review)"
    )
    bullets = "\n".join(f"- {e}" for e in g.evidence) or "- (no terminating signal detected)"
    return (
        f"# {g.run_id} — annotation proposal\n\n"
        f"**Issue.** {g.issue}\n\n"
        f"**Verdict (heuristic):** `{g.verdict}` (confidence: `{g.confidence}`)\n\n"
        f"**Proposed `final_success`:** `{fs}`\n\n"
        f"**Trajectory length:** {g.n_steps} events; last assistant action: "
        f"`{g.last_assistant_action}`.\n\n"
        f"**Evidence.**\n{bullets}\n\n"
        f"**Annotator action.** Review trajectory_summary.md and final_diff.patch. "
        f"Either confirm the proposal, set `final_success` per evidence, or leave it "
        f"`null` with a per-run explanation. Do not let the heuristic verdict bind "
        f"the human read.\n"
    )


def _summary_md(grades: list[HermesGrade]) -> str:
    counts = {"failure": 0, "success_self_claim": 0, "ambiguous": 0}
    for g in grades:
        counts[g.verdict] = counts.get(g.verdict, 0) + 1
    lines = [
        "# Hermes annotation proposal — summary",
        "",
        "_Generated by `scripts/build_hermes_annotation_proposal.py`. "
        "These are **proposals**, not committed labels. T2 (in TASKS.md) requires "
        "the upstream maintainer to review each run before any label lands in "
        "`source_metadata.json`._",
        "",
        "## Verdict distribution (30 runs)",
        "",
        f"- `failure` (low/medium confidence): {counts['failure']}",
        f"- `success_self_claim` (low confidence — agent self-claim only): {counts['success_self_claim']}",
        f"- `ambiguous` (no terminating signal): {counts['ambiguous']}",
        "",
        "## Per-run table",
        "",
        "| run_id | verdict | confidence | proposed final_success | n_steps | last action |",
        "|---|---|---|---|---:|---|",
    ]
    for g in grades:
        proposed = "false" if g.proposed_final_success is False else (
            "true" if g.proposed_final_success is True else "null"
        )
        lines.append(
            f"| {g.run_id} | {g.verdict} | {g.confidence} | {proposed} "
            f"| {g.n_steps} | `{g.last_assistant_action}` |"
        )
    lines += [
        "",
        "## Method",
        "",
        "Conservative deterministic grader, no LLM. Per run:",
        "- `failure` (medium confidence): last 3 tool responses identical and error-shaped (BLOCK pattern), no terminal tool call. **(0 instances in the current 30-run corpus — Hermes runs hit budget exhaustion before a tight error streak forms.)**",
        "- `failure` (low confidence): trajectory hit the iteration budget without a terminal tool call.",
        "- `success_self_claim` (low confidence): agent reached `submit_answer` / `finish` / `skill_manage` / `skill_view`. Self-claim only — there is no verifier.",
        "- `ambiguous`: none of the above. Trajectory ends mid-flight; cannot grade.",
        "",
        "**Never emits `success_verified`.** Hermes ships no eval log; the trace alone cannot prove success.",
        "",
        "## Why this is a proposal, not a label",
        "",
        "T2's acceptance requires `>= 25/30` runs to have **usable** final labels. "
        "The trajectory itself does not provide enough evidence to assert `true` for "
        "open-ended Hermes tasks like 'Write a script that automates running end-to-end "
        "tests'. Setting `final_success=true` from a self-claim alone would fabricate "
        "data (rule § 0.9 in TASKS.md). Hence:",
        "",
        "- `failure` proposals can be promoted to upstream labels by an annotator who "
        "  agrees the BLOCK or budget-exhaust signal closes the trajectory.",
        "- `success_self_claim` proposals require a human read of the produced artifacts "
        "  (`final_diff.patch`, written files) against the issue text before promotion.",
        "- `ambiguous` proposals are starting points, not labels.",
        "",
        "## Handoff",
        "",
        "Per-run proposals live next to this summary. Upstream annotator workflow:",
        "",
        "1. Read this summary.",
        "2. For each run: read trajectory_summary.md, final_diff.patch, run_notes.md.",
        "3. Decide `final_success ∈ {true, false, null}` and `final_success_source ∈ {hermes_human_review_v1, ...}`.",
        "4. Update `runs/hermes_pilot_h5_v2/<run_id>/source_metadata.json` upstream.",
        "5. Update `runs/hermes_pilot_h5_v2/<run_id>/run_notes.md` with the decision.",
        "6. Re-run `coding_estimator.labels.build.write_combined_labels` to pick up labels.",
        "",
        "T3 (rebuild estimator artifacts) is blocked until step 6 succeeds with at "
        "least 25/30 usable labels.",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    if not SOURCE_RUNS.is_dir():
        raise FileNotFoundError(f"upstream Hermes runs not found: {SOURCE_RUNS}")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    grades = grade_source(SOURCE_RUNS)
    if len(grades) != 30:
        raise RuntimeError(
            f"expected 30 hermes_pilot_h5_v2 runs at {SOURCE_RUNS}, got {len(grades)}; "
            f"upstream corpus has changed and this script's pinning needs to be updated"
        )
    for g in grades:
        (OUT_DIR / f"{g.run_id}.md").write_text(_per_run_md(g))
    summary = OUT_DIR.parent / "HERMES_ANNOTATION_PROPOSAL.md"
    summary.write_text(_summary_md(grades))
    print(f"wrote {len(grades)} per-run proposals to {OUT_DIR}")
    print(f"wrote summary to {summary}")


if __name__ == "__main__":
    main()
